name: List services in GCP
on:
  pull_request:
    branches:
      - main
      - feature/*

  workflow_dispatch:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@f1e2d3c4b5a6f7e8d9c0b1a2c3d4e5f6a7b8c9d0'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'https://iam.googleapis.com/projects/282716805542/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github@user-kfktizoyrmin.iam.gserviceaccount.com'

    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
